### ISSUE TITLE
Why not just putting those informations to our domains?

### ISSUE THREAD

**Issue by muratcorlu** [apple/password-manager-resources#100]
Apple already has a good approach for "Universal Links" that forcing domain owners to put a configuration file(`apple-app-site-association`) to their domains for enabling and configuring how they want to use universal links. I think, same approach could be very handy and secure for password rules. As a domain owner we could put a file to our `/password-rules.json` path with content similar and combined as here. And any password manager could check this url before trying to generate a password for it. In this case if a website/app need to change their password rules, process will be very easy, fast and secure.

Why Apple suggests a different -and very hard to maintain in my opinion- approach now? Am I missing something?

An example file that needs to be published at `microsoft.com/password-rules.json`:

```json
{
    "password-rules": "minlength: 8; maxlength: 16;",
    "shared-domains": ["microsoft.com", "live.com"],
    "change-password-url": "https://account.microsoft.com/change-password"
}
```

**Comment by rmondello** [comment]
For password rules, Apple has proposed and implements the `passwordrules` attribute of `<input>`: https://developer.apple.com/documentation/security/password_autofill/customizing_password_autofill_rules

For Change Password URLs, we have the Well-Known URL for Changing Passwords: https://wicg.github.io/change-password-url/

As the README file states, it is preferable for websites to directly use these. If the websites use these, then there’s no need to document them in this central repository. In fact, if a website adopts these, their quirks entries should be removed from this repository!

The shared domains concept is a bit trickier, and there is no mechanism endorsed by Apple for websites to make this kind of claim, at this time.

**Comment by muratcorlu** [comment]
Sorry, I should read readme file more carefully. That's fair. Thanks for your reply.

**Comment by rmondello** [comment]
You’re welcome! If there’s anything you can think of that we could do to make it easier to understand this from the README, let me know, and we’ll try to make it happen! :)
