### ISSUE TITLE
example-xxxxx.com domains

### ISSUE THREAD

**Issue by DerJuulsn** [apple/password-manager-resources#101]
So, I've created the PR #96 and added some websites from German banks.
There is this one bank called Sparkasse, one of the most popular banks in Germany.
But here's the thing. Every district got it's own website like 
www.sparkasse-_putYourDistrictNameInHere_.de 

E.g [_www.sparkasse-aachen.de_](https://www.sparkasse-aachen.de/de/home.html) or [_www.sparkasse-passau.de_](https://www.sparkasse-passau.de/de/home.html)

Could we like add an option to say like "allow the password generation for every domain which follows this specific scheme: **xxxx** "?

I think there are several other websites which are built up like my example.

**Comment by rmondello** [comment]
Interesting! I’m a little nervous about such a syntax, because it could make it too easy to accidentally make a claim about an unintended domain. But maybe you can help me be less nervous about it by proposing such a syntax!

**Comment by igor-makarov** [comment]
It seems like this won't cause any auto-fill to happen, even if the wildcard "hijacks" an unrelated domain. The user would have to have a credential for a "related" domain that isn't related.

There seem to be ~400 districts in Germany, wonder how many have Sparkasse domains. 

By the way, some seem to be outside of this format, e.g. `www.ksk-koeln.de`. Are they the same bank?

I dunno, it seems like an outlier. Can we really deal with it really?

**Comment by DerJuulsn** [comment]
I'll think about a scheme tomorrow. Maybe sth simple like: www.sparkasse-([A-Za-z0-9])\w+.de
While the regex part is just a placeholder which can be replaced in the JSON file with a percent sign or sth like that.

@igor-makarov what do you mean by credential? Sorry, english is my second language :)
Yep, you're right, ksk (Kreissparkasse) is AFAIK an association of a few Sparkassen in a district. Kinda complicated.

Tbh, I don't either. Anyone knows about more such domains?

**Comment by igor-makarov** [comment]
@DerJuulsn credential is something like a password or a PIN.

The thing about "these domains" is that it's not really related to domains. It's entirely up to Sparkasse and how their banking software is structured.

**Comment by m33x** [comment]
Is there any potential way to abuse such a scheme, e.g., by registering www.sparkasse-achen.de (using only one "a" instead of the correct two "aa") and then directing a victim to the wrong/phishing change password page? 

Currently, I cannot come up with a valid attack scenario, but this is something we should think about a little more.

**Comment by DerJuulsn** [comment]
@igor-makarov thanks!

Yeah, you're probably right. I think its easier for them to implement it in their websites than for us :)

**Comment by DerJuulsn** [comment]
@m33x Well, I think if I would implement such a feature, you should just get the rule for this website. If you wanna type your password, it should just  auto-fill on the same domain as the one it where generated on.

**Comment by igor-makarov** [comment]
@m33x this phishing could definitely be possible. Let's be careful with introducing wildcards.

**Comment by rmondello** [comment]
Fundamentally, unless there is a guarantee that a different entity could not register a domain matching a pseudo-wildcard entry, a pattern-based scheme seems unsafe. It would be safer to enumerate known domains.

**Comment by jumoru** [comment]
> Tbh, I don't either. Anyone knows about more such domains?

I think Sparkasse at least has 4 different naming schemes: sparkasse-**xxxx**.de, ksk-**xxxx**.de, stadtsparkasse-**xxxx**.de, ssk**xxxx**.de depending on whether they serve a town or region. Moreover, while I think that all their sites are hosted by a single hosting company (their joint IT department), I don't know whether all Sparkassen actually have the same password requirements.

As mentioned in a [link](https://github.com/dumb-password-rules/dumb-password-rules#sparda-bank) provided in #91 Sparda Bank, which has a comparable URL naming scheme, at least has one branch with different password rules.

**Comment by MaivKhanh** [comment]
1

**Comment by rmondello** [comment]
Going to close this for now. Great discussion!
