### ISSUE TITLE
You’re fine! Thanks for clarifying this. Feel free to bump (comment in) this issue once that change has happened and this seems worth doing!

### ISSUE THREAD

**Issue by MaivKhanh** [apple/password-manager-resources#132]
You’re fine! Thanks for clarifying this. Feel free to bump (comment in) this issue once that change has happened and this seems worth doing!

_Originally posted by @rmondello in https://github.com/apple/password-manager-resources/issues/115#issuecomment-640155295_

**Comment by MaivKhanh** [comment]
> You’re fine! Thanks for clarifying this. Feel free to bump (comment in) this issue once that change has happened and this seems worth doing!
> 
> _Originally posted by @rmondello in https://github.com/apple/password-manager-resources/issues/115#issuecomment-640155295_

**Comment by rmondello** [comment]
Looks like raising an issue here was a mistake. Closing.
