### ISSUE TITLE
HDFC Bank's website password cannot be saved to password managers

### ISSUE THREAD

**Issue by vbGoz** [apple/password-manager-resources#14]
HDFC Bank's website (https://www.hdfcbank.com) randomizes the password before the password managers can save them thus saving incorrect password.

**Comment by rmondello** [comment]
That’s rough, and sounds like no fun. This issue doesn’t exactly fit into the scope of this project as outlined in the README, unless you can conceptualize a website-specific rule for adapting to this behavior.

**Comment by AndiCui** [comment]
I have also encountered some sites that changes the input field before submitting/redirecting. I think this can be made into a quirk that gets the input value the moment before the last click event/a post request goes out.
