### ISSUE TITLE
shared backend appropriate when one domain is a subdomain?

### ISSUE THREAD

**Issue by geoffcline** [apple/password-manager-resources#144]
Is a shared backend group appropriate when one domain is a subdomain?

For example, you enter your seattle public library username/pin on pages served from both these sites:
seattle.bibliocommons.com (library catalog)
spl.overdrive.com (ebooks)
spl.org (access online library resources, eg, databases)

Is the fact this rule only works for "seattle.bibliocommons.com" a problem? 

Consider, the St. Louis Public Library uses:
slpl.bibliocommons.com
slpl.overdrive.com
slpl.org

**Comment by igor-makarov** [comment]
The three domains you listed aren't considered subdomains of each other, therefore listing them as shared credentials is a good idea. However, it appears on first glance that `spl.org` redirects to one of the other domains for login, so it's not necessary to add this one.

**Comment by geoffcline** [comment]
Ok, thanks for this feedback, I will add two different groups for "seattle.bibliocommons.com" and "slpl.bibliocommons.com" 

small note, seattle uses ezproxy.spl.org/login for access to some resources
