### ISSUE TITLE
Is there a security risk for "Websites with shared credential backends"?

### ISSUE THREAD

**Issue by irew** [apple/password-manager-resources#149]
This resource seems like a potential security risk. A malicious contributor could link a malicious website to a genuine one. Coupled with social engineering or phishing, users of password managers may inadvertently autofill credentials on fake websites.

What is the process to vet these entries?

**Comment by igor-makarov** [comment]
This is exactly why these PRs are verified by a human. The evidence required is either DNS entries or SSL certificates or something that verifies that the domains belong to the same backend.

Also, the suggested best practice for password managers is to not autofill but to suggest filling out the password in the case of a shared backend.

**Comment by igor-makarov** [comment]
Opened #150 to clarify.

**Comment by irew** [comment]
Great, thanks for the info @igor-makarov !
