### ISSUE TITLE
[Suggestion] Use JSON fully for password-rules.json 

### ISSUE THREAD

**Issue by rmtmckenzie** [apple/password-manager-resources#159]
Hi - I'm potential target of this repository as I'm working for a startup building a password manager (among other things). I'm very excited about this repository as it might make my life a lot easier once we get done with it!

I have one question for the maintainers though - why was it decided not to use JSON to express the password rules rather than a custom format for the data? If it were to save characters that would be reasonable, but it appears to be a very similar length.

What I'm asking is, why can't this:
```json
{
    "163.com": {
        "password-rules": "minlength: 6; maxlength: 16;"
    },
    ...
```

be this:

```json
{
    "163.com": {
        "password-rules": { "minlength": 6, "maxlength": 16 }
    },
    ...
```
or even better since this entire document is just for password rules (although I could understand doing it the aforementioned way if the document might eventually contain other things as well...) :
```json
{
    "163.com": {
        "minlength": 6, "maxlength": 16
    },
    ...
```

That way there would still need to be some custom logic for it, but it wouldn't necessitate writing a complete custom parser just to extract information from an already structured data format.

If there is enough support for this change I would be more than happy to make a PR converting the document, although I don't know that I have the time to rewrite the parser at this moment.

**Comment by rmondello** [comment]
We’re leveraging the fact that Safari and iOS have been using the passwordRules language for a few years now. Safari supports a `passwordrules` attribute on text fields that uses this language and will generate passwords conforming to rules specified in this way, and UIKit has a concept called `UITextInputPasswordRules`.

What this means, in practice, is that a website could see themselves on this list, decide they’d like to adopt the `passwordrules` attribute on their new-password fields, and directly use the rule. They could then ask to be removed from the list.

I also personally find that the (Validation Tool)[https://developer.apple.com/password-rules/] makes it pretty easy and fun to write these rules as a string. The DSL puts the burden on password manager implementers, optimizing for ease or reading and writing for website authors and quirks authors.

That said, we were sensitive to the fact that parsing isn’t easy and requires care. That’s why we released a reference implementation of a parser. If anyone writes another implementation, they could contribute it to the project, too.

**Comment by jpgoldberg** [comment]
Note again that in the README for this repo there is a link to a Javascript parser for password-rules. I haven't looked at that code as we at 1Password had already built our own. (We've been using password-rules in a couple of places).

**Comment by rmtmckenzie** [comment]
Thanks for the explanation. I totally missed the part of the README about the passwordRules attribute and haven't followed Safari or WhatWG closely enough to be aware of it; that's quite useful (although it is unfortunate that it is needed at all).

Given that the format is "out there" as it were and not just invented for this particular project, I'll close this for now.
