### ISSUE TITLE
[Suggestion] Add URLs for account deletion

### ISSUE THREAD

**Issue by vszakats** [apple/password-manager-resources#165]
As in title, if there is interest in this. Account deletion is part of the normal account/personal-data management life-cycle, and like password updates, it helps if it's easy to find where to do it.

**Comment by igor-makarov** [comment]
This duplicates the discussion in #63.

**Comment by vszakats** [comment]
@igor-makarov Thanks for the link, I skimmed the issues and missed it, sorry! Closing this one.
