### ISSUE TITLE
[Suggestion] Encourage PASSWORD.TXT Files on Servers

### ISSUE THREAD

**Issue by kranzky** [apple/password-manager-resources#170]
I've often thought it would be useful to build a database of password rules and links for login and password reset for websites, so it's great to see this project. But one possible way to flip the responsibility for doing so would be to encourage sites to host a `password.txt` file, similar in nature to `robots.txt`, `ads.txt` and `security.txt`, that would allow them to make this information available themselves.

Perhaps one way of doing this would be to send an official email to the development team for each website that is added to this repository with an attached `password.txt` file that would be suitable for adding to their website (i.e. we would pre-fill the information for them).

Apologies if this is an inappropriate use of your issues list, and I do accept that the gut reaction to this idea will be that it's silly :)

**Comment by hober** [comment]
> I've often thought it would be useful to build a database of password rules and links for login and password reset for websites, so it's great to see this project. But one possible way to flip the responsibility for doing so would be to encourage sites to host a `password.txt` file, similar in nature to `robots.txt`, `ads.txt` and `security.txt`, that would allow them to make this information available themselves.

I agree that, in general, the responsibility should be on sites to make their password rules and change password pages discoverable. This is why we've proposed [adding a passwordrules attribute to HTML](https://github.com/whatwg/html/pull/4000), and why we've written the [A Well-Known URL for Changing Passwords](https://wicg.github.io/change-password-url/) specification.

If there are additional data points that would benefit from being programmatically discoverable, we should make specific standards proposals for each one.

> Perhaps one way of doing this would be to send an official email to the development team for each website that is added to this repository[…]

I think that, over time, we want the various lists in this project to get *smaller* as more and more sites make these things discoverable, and it may very well make sense to contact sites which appear in our lists to encourage them to do so.

**Comment by kranzky** [comment]
Thanks for the info @hober, and apologies for not reading enough to find out about the specs myself. I plan to build passworderulestxt.org as a side project to encourage sites to make password rules discoverable; something I had already considered doing for my own password manager.
