### ISSUE TITLE
Parity with lastpass on password changing links

### ISSUE THREAD

**Issue by superusercode** [apple/password-manager-resources#180]
They have a list on https://helpdesk.lastpass.com/generating-a-password/auto-password-change-beta/ but I am not sure if it is up to date.

**Comment by rmondello** [comment]
It sounds like that LastPass feature might involve a URL like this project has, but it does a lot more. I’m not sure this is really a valid issue; if LastPass would like to contribute URLs, they are free to participate in the project.
