### ISSUE TITLE
Add bargainbox.co.nz and myfoodbag.co.nz to websites-with-shared-credential-backends.json

### ISSUE THREAD

**Issue by mxswd** [apple/password-manager-resources#185]
Same website.

**Comment by sp-magicspells** [comment]
Can we get checklist for this?

**Comment by sp-magicspells** [comment]
Can I take this up?

**Comment by igor-makarov** [comment]
I don't see why not - the issue is 10 days old and you can tag your PR with it, e.g. `Closes #XXX`

**Comment by mxswd** [comment]
MyFoodBag switched them to use Azure B2C, so this is no longer an issue.

A funny issue is since https://myfoodbagidentity.b2clogin.com is the same origin as https://b2cprodcasa.b2clogin.com it now shows my login to https://www.casa.gov.au instead of myfoodbag.
