### ISSUE TITLE
Flickr no longer shares credentials with Yahoo

### ISSUE THREAD

**Issue by wezm** [apple/password-manager-resources#226]
I think this entry should be removed now that [Flickr is migrating away from Yahoo login](https://help.flickr.com/en_us/changes-to-login-featured-rkF1q3cIV).

https://github.com/apple/password-manager-resources/blob/e6ee72184ed39a4420bd8a29db1e13092149c56d/quirks/websites-with-shared-credential-backends.json#L296-L297

**Comment by rmondello** [comment]
Some of the entries from the data that was initially taken from Safari and iCloud Keychain is kind of legacy, and therefore, may still be useful if a user has credentials saved at the old domain. This is a general problem that we might want to address with additional metadata.

However, for now, it seems like this association should be removed.

**Comment by rmondello** [comment]
(If anyone wants to send a PR for this, I’d happily review it!)
