### ISSUE TITLE
Apple

### ISSUE THREAD

**Issue by T-1021** [apple/password-manager-resources#242]

**Comment by T-1021** [comment]
Coming

**Comment by sp-magicspells** [comment]
What is this? Is it kind of some testing from Apple side?

**Comment by igor-makarov** [comment]
More likely spambot of some sort, @rmondello?

**Comment by sp-magicspells** [comment]
Can we close this?

**Comment by rmondello** [comment]
(Sorry for the delay on this one, folks! This one just kind of slipped through.)
