### ISSUE TITLE
Banking domains?

### ISSUE THREAD

**Issue by sp-magicspells** [apple/password-manager-resources#244]
Is it ok to include banking domains here?

**Comment by igor-makarov** [comment]
Of course! There are quite a few added already, for example, BOA, Amex, Capital One to name a few.

**Comment by sp-magicspells** [comment]
@igor-makarov ok. great. I will add some of them to the list. In our local banking websites they really have a lot of constraints. And I myself not used password manager for those sites.

**Comment by Cor109** [comment]
Je

**Comment by Cor109** [comment]
Je
