### ISSUE TITLE
Amazon.cn doesn't share credential backends with other Amazon websites.

### ISSUE THREAD

**Issue by CoolTomatos** [apple/password-manager-resources#279]
https://github.com/apple/password-manager-resources/blob/f547ed1cc40b35d48e758044a2882f052ce0ed4c/quirks/websites-with-shared-credential-backends.json#L20

**Comment by rmondello** [comment]
Ah. Thanks for pointing this out! The fix would be to remove that line from the file.

**Comment by bryanbartow** [comment]
@rmondello PR submitted.

**Comment by rmondello** [comment]
This was resolved by #287.
