### ISSUE TITLE
Three sets of websites that share password back ends

### ISSUE THREAD

**Issue by darinadler** [apple/password-manager-resources#292]
From looking at my own list of passwords and reviewing how the accounts work, it seems that these 3 sets of websites each share password back ends:

audi.com
audiusa.com

myuhc.com
optum.com
optumrx.com

newyorker.com
vanityfair.com

**Comment by bradcush** [comment]
For Audi specifically I was unable to find a login URL for https://www.audi.com itself so I'm not sure if there is a case for a shared back-end with the URLs mentioned here. @darinadler Are you able to confirm that there is in fact a URL which can be used to login under audi.com? While testing, if the USA is specified as a region the you are redirected to login using https://www.audiusa.com/ and France uses https://identity.vwgroup.io/ as another example. (I'm sure there could be more as I found this quickly with very limited testing) https://www.audiusa.com/ also requires a VIN number which makes it a bit difficult to verify by means of creating an account an logging in and the SSL certificates are different for all 3 URLs.

**Comment by bradcush** [comment]
https://www.newyorker.com/ and https://www.vanityfair.com/ indeed have a shared backend which is confirmed by manual testing as well as verifying they use the same SSL certificate registered under "condenast.com". there are likely many more shared back-ends though as they own quite a few brands which I think are worth checking. (https://www.condenast.com/brands-and-markets/brands)

**Comment by darinadler** [comment]
Sorry, I was imprecise about the Audi situation. My personal iCloud Keychain contains these:

apps.audi.com
login.audi.com
audiusa.com

All with the same password. And it’s warning me about password reuse.

I am guessing that apps.audi.com and login.audi.com were used by the Audi iPhone app. I don’t know if there is anything on the www.audi.com website that uses a password.

**Comment by bradcush** [comment]
@darinadler Ok thanks for clarifying, I'm not sure in that case there is anything to act on for Audi. https://login.audi.com asks the user to login using https://www.audiusa.com/ for US accounts at least. If you can provide an example that proves otherwise feel free to include it, thanks!

**Comment by darinadler** [comment]
There are examples. But they are inside an iPhone app, not on a website, and can’t be verified by using a web browser. This is useful for any password manager that deals with passwords both inside the app and the website. So I think they are useful for this project, but research proving that is not possible just using a web browser.

**Comment by darinadler** [comment]
Let me say this another way:

Right now the password management on Apple platforms claims that I am reusing passwords on multiple websites because I use the same password with the Audi app, which seems have stored it under the "apps.audi.com" and "login.audi.com" domains (maybe at two different times), and the Audi website, which stored it under the "audiusa.com" domain.

So there’s a real issue that needs to be fixed for me. Whether this project can supply the necessary data to resolve it, I don’t know. But I am *not* reusing a password across multiple sites, and macOS and iOS and Safari think that I am.

**Comment by aabosh** [comment]
All the mentioned websites are now included in the list of quirks, so I'm closing the issue. If I missed something, please feel free to create a new issue!
