### ISSUE TITLE
indochino.com needs a quirk

### ISSUE THREAD

**Issue by othermaciej** [apple/password-manager-resources#340]
Min-length: 6
Max-length: 15
Must contain at least one digit and one upper case character

<img width="1087" alt="Screen Shot 2020-09-06 at 10 04 56 PM" src="https://user-images.githubusercontent.com/978436/92350172-07321880-f08d-11ea-8afa-b1e514931fd5.png">

**Comment by rmondello** [comment]
Missing information about what/whether special characters are allowed.

**Comment by othermaciej** [comment]
I don't know how to find out for sure which special characters are allowed, other than trial and error. The validity check appears to be server side only. I tried about half of printable ASCII characters that can be typed with a US MacBook Pro keyboard, and I could not find one that was rejected, so I'd guess all are allowed.

**Comment by rmondello** [comment]
Sounds good to me.

**Comment by Cldfire** [comment]
Closed by #372
