### ISSUE TITLE
Security question

### ISSUE THREAD

**Issue by mbierman** [apple/password-manager-resources#344]
This project looks amazing. But I do have a question. I could imagine that this could be used to more quickly make brute force attacks because bad guys would know precisely what the password rules are for a site. What, if anything can be done about this?

**Comment by Cldfire** [comment]
My personal thoughts on this:

All of the information gathered in this repository is from publicly accessible places, meaning an attacker could always discover the information on their own irrespective of the existence of the rules here.

This project is simply aggregating the rules in a single location.

**Comment by mbierman** [comment]
@Cldfire thAt is a valid point. Security through obscurity isn’t very strong anyway. Still, I wonder if there is something clever that can be done to mitigate this harm.

**Comment by rmondello** [comment]
I agree with @Cldfire. I consider this kind of a non-problem. (Although it’s interesting!)

**Comment by ahmedfayd** [comment]
Can I cooperate with you on some matters

في الجمعة، 18 سبتمبر، 2020 11:59 م Ricky Mondello <notifications@github.com>
كتب:

**Comment by aabosh** [comment]
Seems like the discussion surrounding this concluded, so I'm closing the issue. If there are any other thoughts, please feel free to create a new issue!
