### ISSUE TITLE
Add Decluttr to quirks

### ISSUE THREAD

**Issue by carlylemiii** [apple/password-manager-resources#348]
https://www.decluttr.com/register/

<img width="476" alt="CleanShot 2020-09-15 at 07 27 33@2x" src="https://user-images.githubusercontent.com/29067983/93210285-f0db2b00-f724-11ea-839a-1f4b2ac7cab7.png">

**Comment by rmondello** [comment]
Do they allow special characters?

**Comment by carlylemiii** [comment]
They do not (see screenshot).

**Comment by rmondello** [comment]
I saw the screenshot. Sometimes what a website states as requirements is a subset of what’s actually allowed. :)

**Comment by carlylemiii** [comment]
It's not in the requirements themselves, but rather preceding:

> Please do not use symbols, punctuation or any other special characters

**Comment by rmondello** [comment]
The question I asked was totally clearly answered by your screenshot. My eyes just gravitated to the list, and skipped the top! 🤦🏻‍♀️

**Comment by Cldfire** [comment]
I missed that top section in the screenshot myself when initially reading through this.

That's why these password rules are so important, so users don't have to go through this too :joy:
