### ISSUE TITLE
(airfrance.com and klm.com) and (disneyplus.com and espn.com) share a backend.

### ISSUE THREAD

**Issue by conmas** [apple/password-manager-resources#364]
Submitting at the request of @rmondello. https://twitter.com/rmondello/status/1314618080736075776?s=21

airfrance.com and klm.com share the same backend account system.

disneyplus.com and espn.com also share the same backend account system. I tried changing my ESPN account password and logging into Disney+ to confirm that this was the case, and I noticed that their account management pages sometimes fall back to go.com instead. However, I've had Safari save a password for just espn.com before.

![Image 10-9-20 at 12 42 PM](https://user-images.githubusercontent.com/6307014/95614919-f62e4b80-0a2c-11eb-9aab-b7527ce2262d.jpg)

**Comment by Cldfire** [comment]
To add another data point here, if you go to, for example, https://www.espn.com/fantasy/ you'll notice that the iframe containing the login form has an origin URL of https://cdn.registerdisney.go.com, meaning a password manager will end up refusing to fill login information into the frame for an item that only has the espn domain associated with it.

**Comment by conmas** [comment]
Closing because airfrance.com and klm.com have been added to websites-with-shared-backends.json, and because it looks like disneyplus.com and espn.com should not be added.
