### ISSUE TITLE
Need a rule for ring.com

### ISSUE THREAD

**Issue by iKrushYou** [apple/password-manager-resources#379]
![image](https://user-images.githubusercontent.com/1500721/99089606-88c98980-259b-11eb-9fd6-6bc998eab883.png)

Every now and then you come across a website that doesn't accept a keychain-generated password and your only option is to manually enter a password. This will usually lead to the user choosing a more insecure password or the cumbersome task of typing that password manually somewhere and then adding the correct characters. 

It would be nice if you could accept the generated password and then have the ability to edit it to fit the criteria

**Comment by Cldfire** [comment]
Hi! This appears to be more of a Safari-specific issue, which this repository isn't quite the right place for. (This is a gathering place for data that any password manager can make use of).

I'm sure @rmondello would be happy to guide this issue where it needs to go, though 😄

**Comment by rmondello** [comment]
Thanks @Cldfire for triaging and @iKrushYou for filing. Yes, for something like this, you’ll want to file an issue with Apple at feedbackassistant.apple.com.
