### ISSUE TITLE
RFC: Add a new quirk representing "one-way" credential sharing

### ISSUE THREAD

**Issue by Cldfire** [apple/password-manager-resources#389]
This RFC proposes a new type of quirk that would make it possible to represent the concept of "one-way" credential sharing between sites. When compared to the existing shared credentials backends quirk, the new quirk would make it possible to express credential sharing with more precision in certain situations, such as domain redirects and SaaS login sites.

## Background

Our README has [some great background](https://github.com/apple/password-manager-resources#websites-with-shared-credential-backends) on why it's helpful for the repo to maintain a list of websites that share credential backends.

The shared credential backends quirk, as defined by the README, accepts entries that meet the following definition:

> The file quirks/websites-with-shared-credential-backends.json contains a list of groups of websites that share the same credential backend and serve pages where users can sign in, accepting accounts from the others. For example, adding first.website and second.website means that first.website and second.website each serve a page (e.g. first.website/login and second.website/login) where the same accounts are valid for signing in, despite the different domains. It wouldn’t be appropriate to associate google.com.il to google.com because google.com.il redirects to accounts.google.com for sign-in, and google.com.il never serves a login page.

Note that this definition excludes certain situations. I'd like to discuss these situations and the reasoning behind the proposed addition of a new type of quirk as opposed to expanding the scope of shared credential backends.

### Redirects

Redirects are domains that served login pages but were changed at some point in time to redirect to another domain where the same credentials are still valid.

A specific example of this is [discord.com](https://discord.com). [discordapp.com](https://discordapp.com) was [recently changed](https://support.discord.com/hc/en-us/articles/360042987951) to redirect to [discord.com](https://discord.com), a move that caused some confusion amongst users of password managers since logins for `discordapp.com` would not be suggested at `discord.com`.

Other past examples of such situations include [discussions.agilebits.com](https://discussions.agilebits.com) -> [1password.community](https://1password.community) and [me.com](https://me.com) -> [icloud.com](https://icloud.com).

The current definition of the shared credential backends quirk excludes these redirect scenarios, since the domain doing the redirecting doesn't itself serve a login page.

### SaaS Login Pages

Domains that initiate the login process but then redirect to a SaaS provider to complete authorization. Example: both [truecore.org](https://www.truecore.org/) and [sagaftrafcu.org](https://www.sagaftrafcu.org/) initiate authorization with a username and then redirect to [netteller.com](https://www.netteller.com) to complete the login process (and to provide the actual online service).

The current definition of the shared credential backends quirk _technically_ excludes this scenario since the initial pages here don't serve the entirety of the login process.

## Proposed Quirk Format

I'd like to propose the following format for the `quirks/websites-with-one-way-credential-sharing.json` file (name up for debate):

```jsonc
[
    {
        "isRedirect": true,
        "from": [
            "website.com",
            "website.net"
        ],
        "to": [
            "otherwebsite.org"
        ]
    },
    // ...
]
```

This format would allow for specifying the redirect examples described earlier:

```jsonc
[
    {
        "isRedirect": true,
        "from": [
            "discordapp.com"
        ],
        "to": [
            "discord.com"
        ]
    },
    {
        "isRedirect": true,
        "from": [
            "discussions.agilebits.com"
        ],
        "to": [
            "1password.community"
        ]
    },
    {
        "isRedirect": true,
        "from": [
            "me.com"
        ],
        "to": [
            "apple.com",
            "icloud.com"
        ]
    },
    // ...
]
```

as well as the SaaS login examples:

```jsonc
[
    {
        "from": [
            "truecore.org",
            "sagaftrafcu.org"
        ],
        "to": [
            "netteller.com"
        ]
    },
    // ...
]
```

Let's go over the details of this proposed format.

### Details of the Proposed Quirk Format

Similar to the format of the shared credential backends quirk, this quirk has an array at its root, containing each of the quirk's individual entries.

Each entry is an object with the following keys: `from`, `to`, and `isRedirect`.

`from` is an array of domains whose credentials should be shared one-way. This array cannot be empty.

`to` is an array of target domains that any credentials associated with the `from` domains should be allowed to match. This array cannot be empty.

`isRedirect` is a boolean that indicates whether or not the entry reperesents a redirect relationship (meaning logins are no longer served on the `from` domains). In the case of a redirect (such as [discordapp.com](https://discordapp.com) -> [discord.com](https://discord.com)), this would be `true`. In other cases (such as the SaaS login examples), this would be false. Omission of the property means that it is false.

## Reasons for the Proposed Quirk to Exist

* It's a more accurate representation of the intent of the data
  * I'm a strong believer in avoiding generalization where possible
* It allows for more precise enforcement of credential sharing
  * When compared to adding entries to the list of shared credential backends in the case of redirects, this proposed quirk would allow for preventing credentials saved for the destination of a redirect from matching the domain doing the redirect
    * As a specific example, if `discordapp.com` ever came under the control of a new owner, credentials for `discord.com` would not match the domain and whatever new content it may point to
* It enables additional features in password managers
  * A password manager could suggest updating the URL associated with credentials from the old domain to the new domain
    * As a specific example, a password manager could suggest replacing `discordapp.com` with `discord.com`
    * The `isRedirect` property would allow a password manager to understand when this would be a valid suggestion to make

### Q: Why isn't the shared credential backends quirk already appropriate for the SaaS login example?

If we were to use the shared credential backends quirk for the SaaS login example presented above, we'd end up with entries like this:

```jsonc
[
    "truecore.org",
    "netteller.com"
],
[
    "sagaftrafcu.org",
    "netteller.com"
]
```

This associates each site with the SaaS login in a way that doesn't associate the sites themselves with each other.

Unfortunately, the bi-directional nature of the shared credential backends quirk means that any credentials associated with `netteller.com` will now match each of `sagaftrafcu.org` and `truecore.org`, despite the fact that those credentials may not be valid for either site (and will certainly not be valid for both).

Having a concept of a "one-way" credential mapping allows us to avoid this issue.

### Q: Should this new format be combined with the existing shared credential backends format?

Perhaps. That would require changing the existing format; if that route is preferred, it's certainly possible.

**Comment by rmondello** [comment]
Great writeup! I am broadly in favor.

> Q: Should this new format be combined with the existing shared credential backends format?
> 
> Perhaps. That would require changing the existing format; if that route is preferred, it's certainly possible.

I think the framing of the existing format has been giving us trouble throughout the life of the project, and we should clarify its intent/fold it into this proposal, rather than just make a new type of quirk.

**Comment by rmondello** [comment]
@Cldfire Can you tell me more about how exactly you’d use the one-way SaaS Login Pages mapping?

**Comment by Cldfire** [comment]
> I think the framing of the existing format has been giving us trouble throughout the life of the project, and we should clarify its intent/fold it into this proposal, rather than just make a new type of quirk.

That makes sense; I could update this RFC to be less in the way of "add this new quirk" and more in the way of "make the existing quirk more powerful."

One question is, do we want the data for these two separate JSON formats to exist side-by-side in the same file (`shared-credentials.json`), or do we want to keep them in separate files? Keeping the files separate has the advantage of reducing indentation; combining them reduces the overall number of files in the repo.

> Can you tell me more about how exactly you’d use the one-way SaaS Login Pages mapping?

Sure thing 🙂. I came across this specific scenario the other day and thought it would be a good point to bring up in this RFC, so I don't have a large number of examples, but I can expand on what I brought up above.

Here's the flow I'd expect as a user logging into https://www.truecore.org/ with credentials associated with `truecore.org`:

* Fill username (domain: `truecore.org`)
* *wait for navigation to SaaS login*
* Fill password (domain: `netteller.com`)

For that flow to work, the password manager has to understand that the two separate domains (`truecore.org` and `netteller.com`) share credentials in some way. Expressing a one-way relationship implying that credentials for `truecore.org` are valid at `netteller.com` would enable this flow to work. It avoids the problem that this entry in the current shared credential backends quirk would have:

```json
[
    "truecore.org",
    "netteller.com"
],
[
    "sagaftrafcu.org",
    "netteller.com"
]
```

With these entries, credentials associated with `netteller.com` would match pages on `truecore.org`, `sagaftrafcu.org`, and any other entries added for this particular SaaS service (not the behavior we'd like to see).

It's a small quibble to be sure (since this particular situation is rare, and is quickly fixed by associating both domains with a given set of credentials), but it's the sort of small papercut that I think these quirks are well-suited to eliminate.

**Comment by Cldfire** [comment]
## Thoughts on the Format

> I think the framing of the existing format has been giving us trouble throughout the life of the project, and we should clarify its intent/fold it into this proposal, rather than just make a new type of quirk.

I spent some time thinking about this. Here's a couple format ideas I played around with:

<details>
<summary>Intermingled in same file</summary>

```jsonc
[
    // ...
    {
        "shareCredentialBackends": [
            "optumrx.com",
            "optum.com"
        ]
    },
    {
        "shareCredentialBackends": [
            "pinterest.com",
            "pinterest.ca",
            "pinterest.co.uk",
            "pinterest.fr",
            "pinterest.de",
            "pinterest.es",
            "pin.it",
            "pinterest.com.au",
            "pinterest.se",
            "pinterest.ph",
            "pinterest.ch",
            "pinterest.com.mx",
            "pinterest.dk",
            "pinterest.pt",
            "pinterest.ru",
            "pinterest.it",
            "pinterest.at",
            "pinterest.jp",
            "pinterest.cl",
            "pinterest.ie",
            "pinterest.co.kr",
            "pinterest.nz",
            "pintrest.com"
        ],
        "shareCredentialsOneWay": {
            "isRedirect": true,
            "from": [
                "pintrest.com"
            ],
            "to": [
                "pinterest.com"
            ]
        }
    },
    {
        "shareCredentialsOneWay": {
            "isRedirect": true,
            "from": [
                "discordapp.com"
            ],
            "to": [
                "discord.com"
            ]
        }
    }
    // ...
]
```

</details>

This format is interesting in that it allows us to group the redirect information for `pintrest.com` right alongside the shared credential backend information for the same websites (which is nice organization!). The downsides, though, are the visual clutter, more complicated format, and excessive indentation. It's also very difficult to eyeball how to alphabetize it.

<details>
<summary>Separated in same file</summary>

```jsonc
{
    "sharedCredentialBackends": [
        // ...
        [
            "optumrx.com",
            "optum.com"
        ],
        [
            "pinterest.com",
            "pinterest.ca",
            "pinterest.co.uk",
            "pinterest.fr",
            "pinterest.de",
            "pinterest.es",
            "pin.it",
            "pinterest.com.au",
            "pinterest.se",
            "pinterest.ph",
            "pinterest.ch",
            "pinterest.com.mx",
            "pinterest.dk",
            "pinterest.pt",
            "pinterest.ru",
            "pinterest.it",
            "pinterest.at",
            "pinterest.jp",
            "pinterest.cl",
            "pinterest.ie",
            "pinterest.co.kr",
            "pinterest.nz",
            "pintrest.com"
        ]
        // ...
    ],
    "shareCredentialsOneWay": [
        // ...
        {
            "isRedirect": true,
            "from": [
                "pintrest.com"
            ],
            "to": [
                "pinterest.com"
            ]
        },
        {
            "isRedirect": true,
            "from": [
                "discordapp.com"
            ],
            "to": [
                "discord.com"
            ]
        }
        // ...
    ]
}
```

</details>

This format is essentially what I originally proposed, except it's been combined into one file. I can't think of any advantages that this has beyond simply being one file. The major disadvantage is the excessive indentation.

From my point of view, the best course of action here would be to:

* Add the format proposed in this RFC as a new file
* Move the new file and the existing `websites-with-shared-credential-backends.json` into the following folder structure:

```
quirks/
    ...
    credential-mapping/
        websites-with-shared-credential-backends.json
        websites-with-one-way-credential-sharing.json
    ...
```

* Clarify the meaning of the folder and the files within throughout the repository's documentation

The major upsides in my mind here are:

* The folder structure helps indicate that `websites-with-shared-credential-backends.json` and `websites-with-one-way-credential-sharing.json` are two variants of the same type of quirk
* The separate files reduce indentation and the complexity of the JSON format in each file
* Consumers of the data can easily include / process only the files they need
* Other files can be added in the future should we discover that another variant of this quirk is needed

I'm interested to hear others' thoughts on this!

## "redirects" vs. "one-way-credentials"

I've been careful in this RFC to keep the concept of "one-way-credentials" generic over more than just redirects. My motivation for this was the discovery of the SaaS login pages and the realization that allowing credentials to be shared one-way could _slightly_ improve the UX in the two situations I detail above.

This is admittedly weak motivation, however, for the extra complication introduced by being generic in this way. It seems unlikely that the "one-way credential" concept will be used for much other than redirects.

I'm interested to hear if others have any ideas about situations where this genericism could come in handy. If there isn't much to motivate it beyond the SaaS examples I provided, it would probably be better to simply go with `websites-with-redirect-credential-sharing.json` and make it less generic.

**Comment by MartinDevi** [comment]
I would suggest having separate files for:
- Credentials with shared backend (the one which already exists)
- Credentials with SSO (like youtube.com -> google.com)
- Credentials with redirection (like gmail.com -> google.com)
The structure for the 2 later files is identical, but just in terms of semantics, I think it's clearer to have these separate.

**Comment by Cldfire** [comment]
Good thoughts. Keeping each file as small in scope as possible makes sense to me.

I'm not sure I quite understand the following point, however:

> * Credentials with SSO (like youtube.com -> google.com)
> * Credentials with redirection (like gmail.com -> google.com)

What causes you to differentiate between these two situations? As far as I can tell, they both redirect to `accounts.google.com` for auth, so they'd both be considered SSO.

**Comment by Cldfire** [comment]
This RFC has been replaced by https://github.com/apple/password-manager-resources/issues/464.
