### ISSUE TITLE
Same password across multiple websites “false” warning

### ISSUE THREAD

**Issue by DaniSpringer** [apple/password-manager-resources#432]
Please allow me to choose specific instances in which two or more websites will have the same password, as in actuality they are the very same website, even if different URLs.

**Comment by rmondello** [comment]
This seems like a report against a specific password manager, not a suggestion for a quirk or data for this project. Please take this request to the vendor it’s intended for.

**Comment by DaniSpringer** [comment]
> This seems like a report against a specific password manager, not a suggestion for a quirk or data for this project. Please take this request to the vendor it’s intended for.

No

**Comment by DaniSpringer** [comment]
> This seems like a report against a specific password manager, not a suggestion for a quirk or data for this project. Please take this request to the vendor it’s intended for.

??
