### ISSUE TITLE
Quirk change suggestion: wsj.com

### ISSUE THREAD

**Issue by carlylemiii** [apple/password-manager-resources#441]
https://customercenter.wsj.com/account#password?mod=ql

Currently there's only a max-length in the quirk for wsj.com, but there are more restrictions than that:

<img width="860" alt="CleanShot 2021-04-02 at 02 46 02@2x" src="https://user-images.githubusercontent.com/29067983/113394386-c3bb3680-935d-11eb-9192-6fe5d882592a.png">

**Comment by aabosh** [comment]
This has been addressed in #442, so I'm closing the issue. If I missed something, please feel free to create a new issue!
