### ISSUE TITLE
Update Cigna quirk

### ISSUE THREAD

**Issue by carlylemiii** [apple/password-manager-resources#443]
As an update to https://github.com/apple/password-manager-resources/issues/311, cigna.com has updated their requirements; one of those special characters is now _required_:

<img width="453" alt="CleanShot 2021-04-03 at 07 17 00@2x" src="https://user-images.githubusercontent.com/29067983/113478195-eed08380-944c-11eb-99dd-6fcc5ccd8795.png">

**Comment by rmondello** [comment]
Thanks for following up with this information!
