### ISSUE TITLE
RFC: Expand the capabilities of the shared-credential-backends quirk

### ISSUE THREAD

**Issue by Cldfire** [apple/password-manager-resources#464]
This is a v2 of RFC #389. It tweaks the scope to become more "enhance the existing credential sharing quirk format" rather than "add a new credential sharing quirk format". Thanks to @rmondello and others for discussing this with me and helping us all arrive at a wonderful v2 of this RFC!

This RFC proposes modifications to the existing `websites-with-shared-credential-backends.json` file that help it represent more credential sharing relationships across the web with greater precision and clarity than before. It also proposes the addition of a second credentials quirk file that can be used to track historical data that is no longer applicable in the current day.

## Background

Our README has [some great background](https://github.com/apple/password-manager-resources#websites-with-shared-credential-backends) on why it's helpful for the repo to maintain a list of websites that share credential backends.

The shared credential backends quirk, as defined by the README, accepts entries that meet the following definition:

> The file quirks/websites-with-shared-credential-backends.json contains a list of groups of websites that share the same credential backend and serve pages where users can sign in, accepting accounts from the others. For example, adding first.website and second.website means that first.website and second.website each serve a page (e.g. first.website/login and second.website/login) where the same accounts are valid for signing in, despite the different domains. It wouldn’t be appropriate to associate google.com.il to google.com because google.com.il redirects to accounts.google.com for sign-in, and google.com.il never serves a login page.

Note that this definition excludes certain situations. I'd like to discuss these situations and the reasoning behind the modifications to the format that this RFC proposes.

### Redirects

Redirects are domains that served login pages but were changed at some point in time to redirect to another domain where the same credentials are still valid.

A specific example of this is [discord.com](https://discord.com). [discordapp.com](https://discordapp.com) was [recently changed](https://support.discord.com/hc/en-us/articles/360042987951) to redirect to [discord.com](https://discord.com), a move that caused some confusion amongst users of password managers since logins for `discordapp.com` would not be suggested at `discord.com`.

Other past examples of such situations include [discussions.agilebits.com](https://discussions.agilebits.com) -> [1password.community](https://1password.community) and [me.com](https://me.com) -> [icloud.com](https://icloud.com).

The current definition of the shared credential backends quirk excludes these redirect scenarios, since the domain doing the redirecting doesn't itself serve a login page.

### SaaS Login Pages

Domains that initiate the login process but then redirect to a SaaS provider to complete authorization. Example: both [truecore.org](https://www.truecore.org/) and [sagaftrafcu.org](https://www.sagaftrafcu.org/) initiate authorization with a username and then redirect to [netteller.com](https://www.netteller.com) to complete the login process (and to provide the actual online service).

The current definition of the shared credential backends quirk _technically_ excludes this scenario since the initial pages here don't serve the entirety of the login process.

## Proposed Modifications to the Quirk Format

I'd like to propose the following modifications to the existing shared credential backends quirk:

* Rename file from `websites-with-shared-credential-backends.json` to `shared-credentials.json`
* Change file format to:

```jsonc
[
    // One-way credential mapping (ideal for redirect situations)
    {
        "fromDomainsAreObsoleted": true,
        "from": [
            "website.com",
            "website.net"
        ],
        "to": [
            "otherwebsite.org"
        ]
    },
    // Bi-directional credential mapping (same behavior as the existing `websites-with-shared-credential-backends.json` format)
    {
        "shared": [
            "internet.us",
            "internet.com"
        ]
    },
    // ...
]
```

Where `from` and `to` must appear in tandem only, `shared` is mutually exclusive with `from` and `to`, and `fromDomainsAreObsoleted` is only applicable to objects containing both `from` and `to`.

This format would allow for specifying the redirect examples described earlier:

```jsonc
[
    {
        "fromDomainsAreObsoleted": true,
        "from": [
            "discordapp.com"
        ],
        "to": [
            "discord.com"
        ]
    },
    {
        "fromDomainsAreObsoleted": true,
        "from": [
            "discussions.agilebits.com"
        ],
        "to": [
            "1password.community"
        ]
    },
    {
        "fromDomainsAreObsoleted": true,
        "from": [
            "me.com"
        ],
        "to": [
            "apple.com",
            "icloud.com"
        ]
    },
    // ...
]
```

as well as the SaaS login examples:

```jsonc
[
    {
        "from": [
            "truecore.org",
            "sagaftrafcu.org"
        ],
        "to": [
            "netteller.com"
        ]
    },
    // ...
]
```

and finally, it can incorporate all of the existing data currently in `websites-with-shared-credential-backends.json`:

```jsonc
[
    {
        "shared": [
            "amcrestcloud.com",
            "amcrestview.com"
        ],
    },
    {
        "shared": [
            "americastestkitchen.com",
            "cooksillustrated.com",
            "cookscountry.com",
            "onlinecookingschool.com"
        ],
    },
    {
        "shared": [
            "ameritrade.com",
            "tdameritrade.com"
        ],
    },
    {
        "shared": [
            "anylist.com",
            "anylistapp.com"
        ],
    },
    // ...
]
```

Let's go over the details of this proposed format.

### Details of the Proposed Quirk Format

This format replaces the existing format's array of arrays with an array of objects that can contain different types of credential sharing directives.

Each entry is an object with the following valid sets of keys:

* `from`, `to`, and `fromDomainsAreObsoleted` (`fromDomainsAreObsoleted` is optional)
* `shared`

`from` is an array of domains whose credentials should be shared one-way. This array cannot be empty.

`to` is an array of target domains that any credentials associated with the `from` domains should be allowed to match. This array cannot be empty.

`fromDomainsAreObsoleted` is a boolean that indicates whether or not the `from` domains in an entry have been obsoleted by the `to` domains (meaning logins are no longer served on the `from` domains). In the case of a redirect (such as [discordapp.com](https://discordapp.com) -> [discord.com](https://discord.com)), this would be `true`. In other cases (such as the SaaS login examples), this would be false. Omission of the property means that it is false.

`shared` is an array of domains whose credentials should be shared saturated-graph style. This array cannot be empty.

This format can then be deserialized in an untagged fashion in your language of choice. [Rust Example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=72847a7456edccb8c1177cacc7f4107e).

## Reasons for the Format Modification

* It's a more accurate representation of the intent of the data
  * I'm a strong believer in avoiding generalization where possible
* It allows for more precise enforcement of credential sharing
  * When compared to simply adding bi-directional shared credential backend entries in the case of redirects, this proposed format would allow for preventing credentials saved for the destination of a redirect from matching the domain doing the redirect
    * As a specific example, if `discordapp.com` ever came under the control of a new owner, credentials for `discord.com` would not match the domain and whatever new content it may point to
* It could enable additional features in password managers
  * A password manager could suggest updating the URL associated with credentials from an old domain to a new domain
    * As a specific example, a password manager could suggest replacing `discordapp.com` with `discord.com`
    * The `fromDomainsAreObsoleted` property would allow a password manager to understand when this would be a valid suggestion to make

## Additional Quirk File to be Added For Historical Data

This RFC also proposes the addition of a quirks file named `shared-credentials-historical.json`. This file will share the exact same format as `shared-credentials.json` (described above). It was noted during discussion of the original RFC that one shortcoming of the shared credential backends quirk as it currently stands is that there is no way to add a "historical" entry that was true at one point in the past but no longer applies to the present day. Password managers that make use of this data to determine when it's appropriate to show a reused password warning, for example, can benefit greatly from historical entries. Such historical entries don't make sense for other uses of the data, however (such as determining which credentials to suggest in the browser for a given site). Creating a separate file for them provides a home for the data and allows consumers of the repository to choose how they'd like to use historical data.

Figuring out which file to add an entry to is very simple: is the entry still valid right now? If yes, it goes in `shared-credentials.json`. If no, it goes in `shared-credentials-historical.json`.

**Comment by rmondello** [comment]
I approve this without any additional comment. I think this is great.

**Comment by bradcush** [comment]
Everything sounds great to me as well, nothing to add either, thank you!

**Comment by rmondello** [comment]
I’m taking a stab at implementing this.

**Comment by merijndejonge** [comment]
Could we add a label or id to each group, see #589?
This way my software could refer to e.g. the group containing website.com and store properties (such as password rules) for them. Currently, this is a bit clumsy to do.
