### ISSUE TITLE
USPS Account Registration Does Not Work With Password Generator

### ISSUE THREAD

**Issue by taramann** [apple/password-manager-resources#509]
When creating an account on USPS.com, I am unable to generate a password! You can see this in action here: [](https://reg.usps.com/entreg/RegistrationAction_input)

<img width="1552" alt="Screen Shot 2021-08-21 at 10 28 01 AM" src="https://user-images.githubusercontent.com/508657/130330176-47473a14-406b-4e18-b8dc-53d422cfa580.png">

**Comment by rmondello** [comment]
This isn’t an issue to be tracked in this repo. What’s being described here is a Safari bug. Thanks @taramann!
