### ISSUE TITLE
Shared credentials for sites/services that use Microsoft 365 separately

### ISSUE THREAD

**Issue by katagaki** [apple/password-manager-resources#534]
Hello!

How are websites using a hybrid environment (i.e. shared authentication on both the site/service's own websites, and also Microsoft 365) handled? For example:

- University A has their website on universitya.school, and there is a sign-in for students using their student ID and University A password. The authentication passes through **universitya.school**.
- University A also provides Microsoft 365 subscriptions to their students, which goes through Microsoft's authentication domain, **login.microsoftonline.com**. The student also uses their student ID and University A password to sign in here.
- In this case, the password manager may prompt the user to save their password as 2 separate entries (one for universitya.school, one for login.microsoftonline.com), causing a password reuse alert, and requiring the user to update both sites' passwords separately.

Would this scenario be considered a shared credential scenario?

**Comment by ezfe** [comment]
Seems like a 1-way sharing of credentials might be appropriate here, i.e. credentials for universitya.school also appear on login.microsoftonline.com, but the reverse wouldn't be true.
