### ISSUE TITLE
Quirk suggestion: wendys.com

### ISSUE THREAD

**Issue by ukanuk** [apple/password-manager-resources#550]
Signing up for Wendy's rewards at https://order.wendys.com lists these requirements:

6-20 characters in length
one UPPERCASE letter
one lowercase letter
one number
Can use: !#$%*/?^()’{}&+-=_

**Comment by rmondello** [comment]
Those requirements look pretty reasonable to me. At least, iCloud Keychain doesn’t have a problem with them.
