### ISSUE TITLE
Reused passwords

### ISSUE THREAD

**Issue by marcdrobinson** [apple/password-manager-resources#575]
Passwords pref pane warns me of reused passwords for Amazon.com and Ring.com. I am using my Amazon account to log into my Ring account. The same problem occurs with neatorama.com and neatoshop.com. One uses the other to login. There’s no way to merge or group the accounts or to add one URL to the other’s record.

**Comment by artembykov** [comment]
> Passwords pref pane warns me of reused passwords for Amazon.com and Ring.com. I am using my Amazon account to log into my Ring account.

@rmondello Would it be enough to extend #541 with Ring domains?

**Comment by rmondello** [comment]
@artembykov Yes!
