### ISSUE TITLE
[Abuse][Santander] [C120594] Cooperation to remove sensitive information published on GitHub Inc

### ISSUE THREAD

**Issue by CsirtEntelgy** [apple/password-manager-resources#654]
We have detected that this repository (apple/password-manager-resources) is being used to publish leaked sensitive information without authorization, from the following URL(s):

https://github.com/apple/password-manager-resources.git
https://raw.githubusercontent.com/apple/password-manager-resources/03606833f85d686e60be038dc488ffeaf29d98e5/quirks/password-rules.json

This unauthorized use of restricted information represents a security risk of Santander. We need your collaboration to stop this leaked information incident, by getting offline this content from the reported URL(s). If you need more information regarding this incident, please contact our CSIRT 24/7.

Thank you very much for your attention. Looking forward to your reply.

Regards,

**Comment by rmondello** [comment]
I see no argument here that this,

```
    "santander.de": {
        "password-rules": "minlength: 8; maxlength: 12; required: lower, upper; required: digit; allowed: [-!#$%&'()*,.:;=?^{}];"
    },
```

, "represents a security risk of Santander”. I’m closing this issue; please follow up in this thread if you have more information.

**Comment by CsirtEntelgy** [comment]
Dear Mr. Mondello, 

Firstly, thank you for your quick response. 

We wanted to clarify that we totally understand that the purpose of you repository is not fraudulent or malicious.

However, our client does not allow its name to appear publicly in Github repositories without authorization, like happens in this case. As Banco Santander is a registered trademark, these elements like its name, logo, or others, cannot be used without its authorization. With this link, you can check here that Santander is a registered trademark: https://branddb.wipo.int/en/quicksearch/brand/ES5020180M3711042?by=brandName&v=santander&rows=15&sort=score%20desc&start=0&_=1671069079261

If you could remove "Santander" from that line in your repository ( https://github.com/apple/password-manager-resources/blob/03606833f85d686e60be038dc488ffeaf29d98e5/quirks/password-rules.json#L632 ) we would really appreciate it, as we would be able to close our case because the name of our client would no longer be in the file. 

Thank you for your understanding and, also, thank you for your time.

Best regards,

Juan Esteban García Flood
