### ISSUE TITLE
playstation.com -> id.sonyentertainmentnetwork.com

### ISSUE THREAD

**Issue by OmgImAlexis** [apple/password-manager-resources#75]
I can use my details for `playstation.com` to login at `id.sonyentertainmentnetwork.com`.

Often I end up with my password manager saving my details to `playstation.com` which then prevents it showing when I actually login via `id.sonyentertainmentnetwork.com`.

**Comment by rmondello** [comment]
Thanks for reporting this, @OmgImAlexis! If you want to try to edit `websites-with-shared-credential-backends.json` yourself to signal this, go ahead! Otherwise, we’ll get around to adding this a bit later! :)

**Comment by rmondello** [comment]
(Also, anyone else reading this, feel free to submit a fix!)

**Comment by Cor109** [comment]
Corleone

**Comment by Cor109** [comment]
Hello word

**Comment by Cor109** [comment]
**@**

**Comment by Cor109** [comment]
**@**
