### ISSUE TITLE
Link in Readme goes to wrong page

### ISSUE THREAD

**Issue by Andyuu** [apple/password-manager-resources#826]
The link to [...third party](https://github.com/apple/password-manager-resources/blob/main/quirks/websites-that-ask-for-credentials-for-other-services-when-embedded-as-third-party.json) in the Readme goes to the wrong place!

It goes to [the same link but not in the quirks directory!](https://github.com/apple/password-manager-resources/blob/main/websites-that-ask-for-credentials-for-other-services-when-embedded-as-third-party.json)

**Comment by rmondello** [comment]
Thanks @Andyuu!
