### ISSUE TITLE
Bright Horizons Family App link to shared credential

### ISSUE THREAD

**Issue by jhillier-danesmeadesg** [apple/password-manager-resources#827]
The Bright Horizons family app doesn't correctly suggest the password for its domain.  I was hoping to contribute the fix directly, but a bit stumped on finding the Team ID.

Anyway, here is the app in question: https://apps.apple.com/gb/app/bright-horizons-family/id1557887617

Bundle ID: `com.brighthorizons.app`

Domain: `familyapp.brighthorizons.co.uk` (you can visit here and use the app credentials)

Let me know if you need any more information, and sorry I couldn't contribute a fix directly - maybe worth bulking up the tutorial if finding the team ID is easily done if you know how?

**Comment by lnlyssg** [comment]
You can try installing the app on your Mac and then using this guide to get the ID: https://support.addigy.com/hc/en-us/articles/4403542583187-How-To-Get-The-Team-ID-Bundle-ID-and-Code-Requirement. Not sure how you'd get the ID if the dev doesn't allow you to install on macOS though...

**Comment by jhillier-danesmeadesg** [comment]
Thank you! This gave me what I needed to raise a PR directly.
