### ISSUE TITLE
Amazon.co.jp does not share credentials with other Amazon sites

### ISSUE THREAD

**Issue by mkrautz** [apple/password-manager-resources#9]
Hi,

I have separate credentials for Amazon.co.jp and the rest of Amazon.
I also use .com, .co.uk, .de, .fr, .it and .es.

However, the shared credentials descriptions in this repo list Amazon.co.jp as sharing credentials with other Amazon sites:

https://github.com/apple/password-manager-resources/blob/f74c6d0/quirks/websites-with-shared-credential-backends.json#L105

Seems like a bug?

**Comment by gobinathm** [comment]
Guess this issue can be closed as PR [#40](https://github.com/apple/password-manager-resources/pull/40) is now merged
